#!/bin/sh
echo "何年?"
read YYYY
echo "何月?"
read MM
cd ~/blog.yamachaaan.net/blog/data/$YYYY/$MM/
name=`date +%Y-%m-%d`
touch ~/blog.yamachaaan.net/blog/data/$YYYY/$MM/$name-diary.md
echo "---" > "$name-diary.md"
echo "layout: post" >> "$name-diary.md"
echo "pubdata: $name-23:59:59+09:00" >> "$name-diary.md"
echo "title: '$YYYY-$MMのふりかえり'" >> "$name-diary.md"
echo "tags: ['half review']" >> "$name-diary.md"
echo "pagetype: posts" >> "$name-diary.md"
echo "---">> "$name-diary.md"
#!HalfReview
echo "$YYYY-1stHalfのふりかえり。  ">> "$name-diary.md"
echo "まず各期間の目標を挙げる。  ">> "$name-diary.md"
echo "[$YYYY の目標]()"  >> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "- 常にクリエイティブな行動を心がける">> "$name-diary.md"
echo "- 損得勘定ではなく、ワクワクできるかどうかで選択する">> "$name-diary.md"
echo "- 常に自分自身を高めていくことを心がける">> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "$YYYYの目標・方針の1hでの解釈  ">> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "- a" >> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "$YYYYの目標  ">> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "- a" >> "$name-diary.md"
echo "- a" >> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "$YYYY-2hでの目標・方針  ">> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "- a" >> "$name-diary.md"
echo "- a" >> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "" >> "$name-diary.md"

#!MonthlyReview
echo "$YYYY-$MMの目標  ">> "$name-diary.md"
echo "月に各週のふりかえりを挙げる。shuhouは以下の通り。  ">> "$name-diary.md"
#!shuhouを自動で取得する
echo "「みた」の一覧を挙げる。  ">> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "- a" >> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "更新したrepositoryの一覧を挙げる。  ">> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "- a" >> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "$YYYYの数値目標に対しての評価を挙げる。  ">> "$name-diary.md"
echo "毎日blog記事を書く  ">> "$name-diary.md"
echo "12個以上のよんだ記事を書く  ">> "$name-diary.md"
echo "12個以上のQiita記事を書く  ">> "$name-diary.md"
echo "blogの週間アクセスが500を超える  ">> "$name-diary.md"
echo "総括  ">> "$name-diary.md"
echo "良い点  ">> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "- a" >> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "悪い点  ">> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "- a" >> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "$YYYY-の目標  ">> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "- [ ] test">> "$name-diary.md"
echo "" >> "$name-diary.md"
echo "$name-diary.mdファイルを作成しました。"
vim ~/blog.yamachaaan.net/blog/data/$YYYY/$MM/$name-diary.md

